server:
  port: 80

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: test
          uri: "lb://eureka-client"
          predicates:
            - Path=/test
            - Method=GET
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"

